### ISSUE TITLE
初回起動時のエラー

### ISSUE THREAD

**Issue by SouWaka2024** [CuboRex-Development/cugo-arduino-beginner-programming#5]
初回で、CuGo V3iのHPに記載の手順書通りにArduino IDEのインストールと設定を行ったのですが、以下のようなエラーが出ます。つきましては、対応方法をご教授お願いいたします。OSはWINDOWS10です。

【エラーメッセージ】
Sketch uses 67748 bytes (3%) of program storage space. Maximum is 2093056 bytes.
Global variables use 109412 bytes (41%) of dynamic memory, leaving 152732 bytes for local variables. Maximum is 262144 bytes.
Resetting COM4
Converting to uf2, output size: 172032, start address: 0x2000
Scanning for RP2040 devices
Flashing D: (RPI-RP2)
Traceback (most recent call last):
  File "C:\Users\setnote\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\3.9.2/tools/uf2conv.py", line 447, in <module>
    main()
  File "C:\Users\setnote\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\3.9.2/tools/uf2conv.py", line 432, in main
    write_file(d + "/NEW.UF2", outbuf)
  File "C:\Users\setnote\AppData\Local\Arduino15\packages\rp2040\hardware\rp2040\3.9.2/tools/uf2conv.py", line 325, in write_file
    with open(name, "wb") as f:
PermissionError: [Errno 13] Permission denied: 'D:/NEW.UF2'
Failed uploading: uploading error: exit status 1

**Comment by abudori3939** [comment]
お送りいただきましたエラー文ですが、コードのエラーではなく、環境の設定によって書き込めない状況のように思えます。
ポートの書き込み権限が取得できないため書き込みできませんでした、という内容のエラーなので以下のWebサイトを参考にしてポートのご確認をお願いいたします。
https://gyorgybalassy.wordpress.com/2020/10/16/cant-open-device-com-access-is-denied-arduino-upload/
